services:
  portal:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: sh -c "npm run dev --workspace=@brio-md/portal"
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://brio:briopassword@db:5432/brio_md
      AUTH_SECRET: +vlyups9ne/PEowaxU/hrmUHY7LxJA31Gv7YiSUZNlo=
      AUTH_TRUST_HOST: "true"
      NEXTAUTH_URL: http://localhost:3002
    volumes:
      - ./apps/portal/src:/app/apps/portal/src
      - ./packages/ui/src:/app/packages/ui/src
      - ./packages/db/src:/app/packages/db/src
      - ./packages/auth/src:/app/packages/auth/src
    ports:
      - "3002:3000"
    depends_on:
      db:
        condition: service_healthy

  learn:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: sh -c "npm run dev --workspace=@brio-md/learn"
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://brio:briopassword@db:5432/brio_md
      AUTH_SECRET: +vlyups9ne/PEowaxU/hrmUHY7LxJA31Gv7YiSUZNlo=
      AUTH_TRUST_HOST: "true"
      NEXTAUTH_URL: http://localhost:3003
    volumes:
      - ./apps/learn/src:/app/apps/learn/src
      - ./packages/ui/src:/app/packages/ui/src
      - ./packages/db/src:/app/packages/db/src
      - ./packages/auth/src:/app/packages/auth/src
    ports:
      - "3003:3000"
    depends_on:
      db:
        condition: service_healthy

  landing:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: sh -c "npm run dev --workspace=@brio-md/landing"
    environment:
      NODE_ENV: development
    volumes:
      - ./apps/landing/src:/app/apps/landing/src
    ports:
      - "3001:3000"
