import {
  ColorPreset,
  AccentPreset,
  ShadowPreset,
  SurfacePreset,
  RadiusPreset,
  PatternPreset,
  FontPreset,
  BorderWidthPreset,
  HoverPreset,
  DensityPreset,
  BrioThemeConfig,
} from "./themeTypes";

export const COLOR_PRESETS: ColorPreset[] = [
  { name: "Slate Implicit", hex: "#f8fafc", category: "Luminos" },
  { name: "Alb Pur", hex: "#ffffff", category: "Luminos" },
  { name: "Gri Apple", hex: "#f5f5f7", category: "Luminos" },
  { name: "Zinc Modern", hex: "#f4f4f5", category: "Luminos" },
  { name: "Perlă Caldă", hex: "#fafaf9", category: "Luminos" },
  { name: "Mentă Proaspătă", hex: "#f0fdf4", category: "Pastel" },
  { name: "Gheață Bleu", hex: "#f0f6fc", category: "Pastel" },
  { name: "Hârtie Caldă", hex: "#fcfaf6", category: "Pastel" },
  { name: "Nisip Fin", hex: "#f7f4ed", category: "Pastel" },
  { name: "Piersică / Rose", hex: "#fff1f2", category: "Pastel" },
  { name: "Lavandă Delicată", hex: "#faf5ff", category: "Pastel" },
  { name: "Chihlimbar Cald", hex: "#fffbeb", category: "Pastel" },
  { name: "Midnight Slate", hex: "#0f172a", category: "Întunecat" },
  { name: "Deep Navy", hex: "#0a1128", category: "Întunecat" },
  { name: "Carbon Zinc", hex: "#18181b", category: "Întunecat" },
  { name: "OLED Black", hex: "#000000", category: "Întunecat" },
];

export const ACCENT_PRESETS: AccentPreset[] = [
  { id: "blue", name: "Albastru Electric", hex: "#2563eb", twClass: "bg-blue-600" },
  { id: "indigo", name: "Indigo / Violet", hex: "#6366f1", twClass: "bg-indigo-600" },
  { id: "emerald", name: "Smarald Verde", hex: "#059669", twClass: "bg-emerald-600" },
  { id: "rose", name: "Trandafiriu / Rose", hex: "#e11d48", twClass: "bg-rose-600" },
  { id: "amber", name: "Chihlimbar / Aur", hex: "#d97706", twClass: "bg-amber-600" },
  { id: "cyan", name: "Cyan / Turcoaz", hex: "#0891b2", twClass: "bg-cyan-600" },
  { id: "purple", name: "Purpuriu Regal", hex: "#9333ea", twClass: "bg-purple-600" },
  { id: "slate", name: "Slate Minimal", hex: "#334155", twClass: "bg-slate-700" },
];

export const SHADOW_PRESETS: ShadowPreset[] = [
  { id: "none", name: "Plat (Flat)", description: "Fără umbră, stil minimalist clar", value: "none" },
  { id: "subtle", name: "Subtil", description: "Umbră discretă de 1px", value: "0 1px 3px 0 rgba(0, 0, 0, 0.05), 0 1px 2px -1px rgba(0, 0, 0, 0.04)" },
  { id: "modern", name: "Modern Brio", description: "Echilibrat, elegant pentru UI", value: "0 4px 6px -1px rgba(0, 0, 0, 0.06), 0 2px 4px -2px rgba(0, 0, 0, 0.04)" },
  { id: "floating", name: "Plutitor (Air)", description: "Carduri ce plutesc deasupra paginii", value: "0 12px 24px -6px rgba(0, 0, 0, 0.08), 0 6px 12px -4px rgba(0, 0, 0, 0.03)" },
  { id: "deep", name: "Adânc 3D", description: "Contrast volumetric puternic", value: "0 20px 28px -8px rgba(0, 0, 0, 0.14), 0 10px 14px -6px rgba(0, 0, 0, 0.07)" },
  { id: "glow_blue", name: "Neon Bleu", description: "Halou luminos albastru modern", value: "0 0 22px -3px rgba(59, 130, 246, 0.22), 0 4px 8px -2px rgba(0, 0, 0, 0.04)" },
  { id: "glow_amber", name: "Chihlimbar Cald", description: "Aura caldă de apus", value: "0 0 22px -3px rgba(245, 158, 11, 0.22), 0 4px 8px -2px rgba(0, 0, 0, 0.04)" },
  { id: "glow_emerald", name: "Aura Smarald", description: "Lumină proaspătă verde", value: "0 0 22px -3px rgba(16, 185, 129, 0.22), 0 4px 8px -2px rgba(0, 0, 0, 0.04)" },
];

export const SURFACE_PRESETS: SurfacePreset[] = [
  { id: "solid", name: "Alb Opac", description: "Card clasic alb solid", bg: "#ffffff", blur: "none", border: "#e2e8f0" },
  { id: "glass", name: "Sticlă Subtilă", description: "88% alb cu blur discret", bg: "rgba(255, 255, 255, 0.88)", blur: "blur(12px)", border: "rgba(255, 255, 255, 0.65)" },
  { id: "frosted", name: "Frosted Glass", description: "72% alb cu blur intens de sticlă mată", bg: "rgba(255, 255, 255, 0.72)", blur: "blur(20px)", border: "rgba(255, 255, 255, 0.85)" },
  { id: "translucent", name: "Translucid", description: "55% alb, efect aerian", bg: "rgba(255, 255, 255, 0.55)", blur: "blur(16px)", border: "rgba(255, 255, 255, 0.5)" },
  { id: "cream", name: "Hârtie Fină", description: "Nuanță caldă de bumbac", bg: "#fdfbf7", blur: "none", border: "#e7e2d9" },
];

export const RADIUS_PRESETS: RadiusPreset[] = [
  { id: "none", name: "Drept (0px)", radius: "0px", pxLabel: "0px" },
  { id: "sm", name: "Subtil (8px)", radius: "0.5rem", pxLabel: "8px" },
  { id: "md", name: "Compact (12px)", radius: "0.75rem", pxLabel: "12px" },
  { id: "lg", name: "Standard (16px)", radius: "1rem", pxLabel: "16px" },
  { id: "xl", name: "Modern (20px)", radius: "1.25rem", pxLabel: "20px" },
  { id: "2xl", name: "Pufos (24px)", radius: "1.5rem", pxLabel: "24px" },
  { id: "3xl", name: "Super Rotunjit", radius: "2rem", pxLabel: "32px" },
];

export const PATTERN_PRESETS: PatternPreset[] = [
  { id: "none", name: "Solid", description: "Fără textură, simplu și clar", icon: "▫️" },
  { id: "dots", name: "Puncte Subtile", description: "Matrice fină de puncte de fundal", icon: "⁖" },
  { id: "grid", name: "Grid Blueprint", description: "Grilă fină arhitecturală", icon: "⌗" },
  { id: "mesh", name: "Ambient Mesh", description: "Aureole de lumină în colțuri", icon: "✨" },
  { id: "diagonal", name: "Linii Diagonale", description: "Dungi discrete înclinate", icon: "▨" },
];

export const FONT_PRESETS: FontPreset[] = [
  { id: "system", name: "Sistem Curat", fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif', preview: "Modern & Rapid" },
  { id: "inter", name: "Inter UI", fontFamily: '"Inter", -apple-system, sans-serif', preview: "Design Tech" },
  { id: "rounded", name: "Rotunjit Prietenos", fontFamily: '"Nunito", "Quicksand", system-ui, sans-serif', preview: "Cald & Prietenos" },
  { id: "mono", name: "Monospace Code", fontFamily: '"JetBrains Mono", "SF Mono", monospace', preview: "Stil Inginerie" },
  { id: "editorial", name: "Editorial Serif", fontFamily: 'ui-serif, Georgia, Cambria, serif', preview: "Clasic & Elegant" },
];

export const BORDER_WIDTH_PRESETS: BorderWidthPreset[] = [
  { id: "none", name: "Fără bordură (0px)", width: "0px" },
  { id: "thin", name: "Fină (1px)", width: "1px" },
  { id: "medium", name: "Pronunțată (2px)", width: "2px" },
];

export const HOVER_PRESETS: HoverPreset[] = [
  { id: "none", name: "Static", description: "Fără animație pe hover" },
  { id: "lift", name: "Plutire (Lift)", description: "Cardul se ridică cu 3px pe hover" },
  { id: "glow", name: "Halo Glow", description: "Aura de lumină intensificată pe hover" },
  { id: "scale", name: "Micro Zoom", description: "Mărire discretă de 1.01x" },
];

export const DENSITY_PRESETS: DensityPreset[] = [
  { id: "compact", name: "Compact", description: "Spațiere densă, vizibilitate maximă de date" },
  { id: "normal", name: "Confortabil", description: "Echilibrul clasic Brio" },
  { id: "relaxed", name: "Aerisit", description: "Spații generoase și relaxate" },
];

export const CURATED_THEMES: BrioThemeConfig[] = [
  {
    name: "Brio Default",
    bg: "#f8fafc",
    accentColor: "#2563eb",
    shadowId: "modern",
    surfaceId: "solid",
    radiusId: "lg",
    patternId: "none",
    fontId: "system",
    borderWidthId: "thin",
    hoverId: "none",
    densityId: "normal",
    headerGlass: false,
  },
  {
    name: "Apple Studio",
    bg: "#f5f5f7",
    accentColor: "#0284c7",
    shadowId: "floating",
    surfaceId: "glass",
    radiusId: "2xl",
    patternId: "mesh",
    fontId: "system",
    borderWidthId: "thin",
    hoverId: "lift",
    densityId: "normal",
    headerGlass: true,
  },
  {
    name: "Mentă Proaspătă",
    bg: "#f0fdf4",
    accentColor: "#059669",
    shadowId: "glow_emerald",
    surfaceId: "frosted",
    radiusId: "2xl",
    patternId: "dots",
    fontId: "rounded",
    borderWidthId: "thin",
    hoverId: "glow",
    densityId: "normal",
    headerGlass: true,
  },
  {
    name: "Nordic Blueprint",
    bg: "#f0f6fc",
    accentColor: "#0284c7",
    shadowId: "subtle",
    surfaceId: "frosted",
    radiusId: "md",
    patternId: "grid",
    fontId: "mono",
    borderWidthId: "thin",
    hoverId: "lift",
    densityId: "compact",
    headerGlass: true,
  },
  {
    name: "Neo-Brutalist",
    bg: "#fafaf9",
    accentColor: "#000000",
    shadowId: "none",
    surfaceId: "solid",
    radiusId: "none",
    patternId: "none",
    fontId: "inter",
    borderWidthId: "medium",
    hoverId: "none",
    densityId: "compact",
    headerGlass: false,
  },
  {
    name: "Hârtie & Bumbac",
    bg: "#f7f4ed",
    accentColor: "#b45309",
    shadowId: "subtle",
    surfaceId: "cream",
    radiusId: "md",
    patternId: "diagonal",
    fontId: "editorial",
    borderWidthId: "thin",
    hoverId: "none",
    densityId: "relaxed",
    headerGlass: false,
  },
  {
    name: "Lavandă Pufos",
    bg: "#faf5ff",
    accentColor: "#9333ea",
    shadowId: "floating",
    surfaceId: "glass",
    radiusId: "3xl",
    patternId: "mesh",
    fontId: "rounded",
    borderWidthId: "thin",
    hoverId: "scale",
    densityId: "relaxed",
    headerGlass: true,
  },
  {
    name: "Piersică Caldă",
    bg: "#fff1f2",
    accentColor: "#e11d48",
    shadowId: "modern",
    surfaceId: "frosted",
    radiusId: "2xl",
    patternId: "dots",
    fontId: "rounded",
    borderWidthId: "thin",
    hoverId: "glow",
    densityId: "normal",
    headerGlass: true,
  },
  {
    name: "Cyber Midnight",
    bg: "#0f172a",
    accentColor: "#38bdf8",
    shadowId: "glow_blue",
    surfaceId: "solid",
    radiusId: "xl",
    patternId: "grid",
    fontId: "mono",
    borderWidthId: "thin",
    hoverId: "glow",
    densityId: "compact",
    headerGlass: true,
  },
  {
    name: "Deep Navy Space",
    bg: "#0a1128",
    accentColor: "#6366f1",
    shadowId: "deep",
    surfaceId: "glass",
    radiusId: "xl",
    patternId: "mesh",
    fontId: "inter",
    borderWidthId: "thin",
    hoverId: "lift",
    densityId: "normal",
    headerGlass: true,
  },
  {
    name: "Apus Chihlimbar",
    bg: "#fffbeb",
    accentColor: "#d97706",
    shadowId: "glow_amber",
    surfaceId: "glass",
    radiusId: "2xl",
    patternId: "mesh",
    fontId: "system",
    borderWidthId: "thin",
    hoverId: "glow",
    densityId: "relaxed",
    headerGlass: true,
  },
];

export const DEFAULT_THEME: BrioThemeConfig = CURATED_THEMES[0];
